
export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Classic Solitaire Ring",
    price: 48500,
    image: "https://placehold.co/400x400/f5f3eb/d4af37.png?text=Ring",
    category: "Rings",
    filterTab: "gold",
    weight: "2.5 g",
    purity: "22K",
  },
  {
    id: "2",
    name: "Temple Necklace",
    price: 125000,
    image: "https://placehold.co/400x400/f5f3eb/d4af37.png?text=Necklace",
    category: "Necklaces",
    filterTab: "gold",
    weight: "18 g",
    purity: "22K",
  },
  {
    id: "3",
    name: "Traditional Bangle Set",
    price: 89000,
    image: "https://placehold.co/400x400/f5f3eb/d4af37.png?text=Bangle",
    category: "Bangles",
    filterTab: "gold",
    weight: "32 g",
    purity: "22K",
  },
  {
    id: "4",
    name: "Bridal Haram",
    price: 285000,
    image: "https://placehold.co/400x400/f5f3eb/d4af37.png?text=Bridal",
    category: "Bridal Sets",
    filterTab: "bridal",
    weight: "85 g",
    purity: "22K",
  },
  {
    id: "5",
    name: "Minimalist Studs",
    price: 12000,
    image: "https://placehold.co/400x400/f5f3eb/d4af37.png?text=Studs",
    category: "Rings",
    filterTab: "gold",
    weight: "0.8 g",
    purity: "24K",
  },
  {
    id: "6",
    name: "Chain with Pendant",
    price: 42000,
    image: "https://placehold.co/400x400/f5f3eb/d4af37.png?text=Chain",
    category: "Necklaces",
    filterTab: "gold",
    weight: "6 g",
    purity: "22K",
  },
  {
    id: "7",
    name: "Silver Oxidised Earrings",
    price: 3500,
    image: "https://placehold.co/400x400/f5f3eb/d4af37.png?text=Silver",
    category: "Earrings",
    filterTab: "silver",
    weight: "8 g",
    purity: "92.5",
  },
  {
    id: "8",
    name: "Gold Coin 1g",
    price: 6500,
    image: "https://placehold.co/400x400/f5f3eb/d4af37.png?text=Coin",
    category: "Coins",
    filterTab: "coins",
    weight: "1 g",
    purity: "24K",
  },
];

export const MOCK_SCHEMES = [
  {
    id: "gold-6",
    name: "6-Month Gold Plan",
    monthlyAmount: 5000,
    durationMonths: 6,
    type: "gold" as const,
    bonus: "No making charges on redemption.",
  },
  {
    id: "gold-11",
    name: "11-Month Gold Plan",
    monthlyAmount: 10000,
    durationMonths: 11,
    type: "gold" as const,
    bonus: "1 month free. Bonus gold on maturity.",
  },
  {
    id: "silver-12",
    name: "12-Month Silver Plan",
    monthlyAmount: 2500,
    durationMonths: 12,
    type: "silver" as const,
    bonus: "5% extra silver on completion.",
  },
];

export const CATEGORIES = [
  { slug: "rings", label: "Rings" },
  { slug: "necklaces", label: "Necklaces" },
  { slug: "bangles", label: "Bangles" },
  { slug: "bridal-sets", label: "Bridal Sets" },
];
